version: "3"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "warehouse-management-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=warehouse
      - POSTGRES_USER=warehouseuser
      - POSTGRES_PASSWORD=warehousepassword
